### ISSUE TITLE
cannot parse this url ?

### ISSUE THREAD

**Issue by nodoubtman** [garretlab/shoddyxml2#1]
Hello.
I tried to parse this url: https://ici.radio-canada.ca/rss/4159

no results...

can you help?
THanks.
Marc.

**Comment by garretlab** [comment]
https://ici.radio-canada.ca/rss/4159 dose not have <?xml>.

If you would like to parse the URL, change two lines in shoddyxml.cpp,

line 10:
this->xmlStarted = 0; to 
this->xmlStarted = 1;

line 91:
xmlStarted = 0; to 
xmlStarted = 1;

**Comment by nodoubtman** [comment]
Thank you :)

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by nodoubtman** [comment]
> 
> 
> https://ici.radio-canada.ca/rss/4159 dose not have <?xml>.
> 
> If you would like to parse the URL, change two lines in shoddyxml.cpp,
> 
> line 10:
> this->xmlStarted = 0; to
> this->xmlStarted = 1;
> 
> line 91:
> xmlStarted = 0; to
> xmlStarted = 1;

Hey, do you mean line 138 ?
i dont see it at line 91 ...
thanks.
Marc.

**Comment by garretlab** [comment]
Only line 12.

I got confused with shoddyxml not shoddyxml2.

**Comment by garretlab** [comment]
Closed.
