### ISSUE TITLE
Doesnt seems to work no more.. :o(

### ISSUE THREAD

**Issue by nodoubtman** [garretlab/shoddyxml2#2]
Try this code and you will see:

#include <WiFi.h>
#include <rssClass.h>

const char* ssid      = "ssid";
const char* password  = "password";

const char *url = "https://montreal.ctvnews.ca/rss/ctv-news-montreal-1.822366";
const char *tag = "title";

rssClass reader;
const int rssArticleSize = 128;
const int rssNumArticle  = 20;
const int rssGetInterval = 1800;

void setup() {
  Serial.begin(115200);

  WiFi.begin(ssid, password);
  Serial.printf("Connecting to WiFi ... ");
  while (WiFi.status() != WL_CONNECTED) {
    delay(1000);
  

> }

  Serial.printf("done.\n");

  configTime(-5 * 3600L, 0, "time.google.com");
  setenv("TZ", "EST5EDT, M3.2.0, M11.1.0", 1);
}

void loop() {
  struct tm timeInfo;
  char header[32];

  getLocalTime(&timeInfo);
  sprintf(header, "News at %04d/%02d/%02d%02d:%02d",
          timeInfo.tm_year + 1900, timeInfo.tm_mon + 1, timeInfo.tm_mday,
          timeInfo.tm_hour, timeInfo.tm_min);
  Serial.printf("\n % s\n", header);

  int n = reader.getArticles(url, tag, rssArticleSize, rssNumArticle);
  for (int i = 0; i < n; i++) {
    Serial.printf("%2d:%s\n", i, reader.itemData[i]);
  }
  delay(rssGetInterval * 1000);
}

thanks.
marc.

**Comment by nodoubtman** [comment]
> 
> 
> Try this code and you will see:
> 
> #include <WiFi.h>
> #include <rssClass.h>
> 
> const char* ssid = "ssid";
> const char* password = "password";
> 
> const char *url = "https://montreal.ctvnews.ca/rss/ctv-news-montreal-1.822366";
> const char *tag = "title";

/*
even these urls doesnt work :o(
*/

const char* ctv_nouvelles_url            = "https://montreal.ctvnews.ca/rss/ctv-news-montreal-1.822366";
const char* tva_nouvelles_url            = "https://www.tvanouvelles.ca/rss.xml";
const char* radio_canada_nouvelles_url   = "https://ici.radio-canada.ca/rss/4159";
const char* google_nouvelles_url         = "https://news.google.com/rss?&hl=fr-CA&gl=CA&ceid=CA:fr";
const char* journal_de_mtl_nouvelles_url = "https://www.journaldemontreal.com/actualite/faits-divers/rss.xml";
const char* la_presse_nouvelles_url      = "https://www.lapresse.ca/manchettes/rss";
> 
> rssClass reader;
> const int rssArticleSize = 128;
> const int rssNumArticle = 20;
> const int rssGetInterval = 1800;
> 
> void setup() {
> Serial.begin(115200);
> 
> WiFi.begin(ssid, password);
> Serial.printf("Connecting to WiFi ... ");
> while (WiFi.status() != WL_CONNECTED) {
> delay(1000);
> }
> Serial.printf("done.\n");
> 
> configTime(-5 * 3600L, 0, "time.google.com");
> setenv("TZ", "EST5EDT, M3.2.0, M11.1.0", 1);
> }
> 
> void loop() {
> struct tm timeInfo;
> char header[32];
> 
> getLocalTime(&timeInfo);
> sprintf(header, "News at %04d/%02d/%02d%02d:%02d",
> timeInfo.tm_year + 1900, timeInfo.tm_mon + 1, timeInfo.tm_mday,
> timeInfo.tm_hour, timeInfo.tm_min);
> Serial.printf("\n % s\n", header);
> 
> int n = reader.getArticles(url, tag, rssArticleSize, rssNumArticle);
> for (int i = 0; i < n; i++) {
> Serial.printf("%2d:%s\n", i, reader.itemData[i]);
> }
> delay(rssGetInterval * 1000);
> }
> 
> thanks.
> marc.

**Comment by nodoubtman** [comment]
ok with esp32 v 1.0.6 doesnt work only with 1.0.4 and above :)

**Comment by garretlab** [comment]
My guess is that you are failing to connect to HTTPS sites.

From the Arduino core for the ESP32 v1.0.5, we need to provide root CA by default or need to use setInsecure() not to provide root CA.
