### ISSUE TITLE
Doesnt work with ESP32 1.0.5 Arduino Core

### ISSUE THREAD

**Issue by nodoubtman** [garretlab/shoddyxml2#3]
Hello. It doesnt work with the 1.0.5 Arduino Core but with 1.0.4 it is ok

thanks.
marc.

**Comment by garretlab** [comment]
It works at my environment, Arduino core for the ESP32 v1.0.6.

Check if you really feed the XML stream to the library.
My guess is that you are failing to connect to HTTPS sites.
From the Arduino core for the ESP32 v1.0.5, we need to provide root CA by default to connect to HTTPS sites or need to use setInsecure() not to provide root CA.

**Comment by garretlab** [comment]
I have updated the rssClass to work with Arduino core for the ESP32 v1.0.6.
But now it dose not work with v1.0.4 or less.

**Comment by garretlab** [comment]
No response for about a month. Closed.
